# Auto-generated by rylai. Do not edit manually.

# ruff: noqa: E501
from __future__ import annotations

import sys
import typing as t

if sys.version_info < (3, 11):
    from typing_extensions import Unpack
else:
    from typing import Unpack
from .typing import (
    BBox,
    Color,
    Point,
    TfSettingItems,
    WordsExtractSettingsItems,
)

# Module: tablers
__version__: t.Final[str]

@t.final
class PdfiumRuntime:
    """
    A wrapper around the Pdfium library runtime.

    This struct holds the Pdfium instance and provides methods to interact with PDF documents.
    It is unsendable because the underlying Pdfium library is not thread-safe.
    """
    def __init__(self, path: str) -> None:
        """
        Creates a new PdfiumRuntime instance by loading the Pdfium library from the specified path.

        If the library has already been initialized, the existing instance is reused
        and the provided path is ignored.

        # Arguments

        * `path` - The file path to the Pdfium dynamic library.

        # Returns

        A new `PdfiumRuntime` instance or a Python error if the library fails to load.
        """

    @staticmethod
    def is_initialized() -> bool:
        """Returns whether the Pdfium library has been initialized."""

@t.final
class Pyo3Doc:
    """
    Represents an opened PDF document.

    This struct provides methods to access pages and metadata of a PDF document.
    The document can be closed explicitly, after which all operations will fail.
    """
    def __init__(
        self,
        runtime: PdfiumRuntime,
        path: str | None = None,
        bytes: bytes | None = None,
        password: str | None = None,
    ) -> None:
        """
        Creates a new Pyo3Doc instance from a file path or bytes.

        # Arguments

        * `runtime` - The PdfiumRuntime instance to use.
        * `path` - Optional file path to the PDF document.
        * `bytes` - Optional PDF content as bytes.
        * `password` - Optional password for encrypted PDFs.

        # Returns

        A new `Pyo3Doc` instance or a Python error if the document cannot be opened.

        # Note

        Either `path` or `bytes` must be provided, but not both.
        """

    def close(self) -> None:
        """close the document, all the pages would be invalid"""

    def is_closed(self) -> bool:
        """
        Checks if the document has been closed.

        # Returns

        `true` if the document is closed, `false` otherwise.
        """

    def save_to_bytes(self) -> bytes:
        """
        Serialize the document to bytes, **always without encryption**.

        Internally this creates a brand-new, empty PDF document, copies every page
        from the current document into it, and serializes the result via
        `FPDF_SaveAsCopy`.  Because the destination document carries no security
        settings, the returned bytes can always be opened without a password—even
        when the source was an encrypted PDF that was unlocked with a password.

        # Warning

        If the original document was password-protected, calling this method
        effectively **strips the encryption**.  The caller is responsible for
        ensuring this is intentional and appropriate for their use case.

        # Performance

        This method is **not** cheap: it allocates and populates a new in-memory
        PDF document on every call.  For large documents the peak memory usage
        will temporarily reach ~2× the document size.  Do not call this in a
        tight loop or on every request; cache the result if you need it more than once.

        # Returns

        The serialized PDF bytes, or a Python error if the document is closed or
        serialization fails.
        """

    def page_count(self) -> int:
        """
        Returns the total number of pages in the document.

        # Returns

        The page count or a Python error if the document is closed.
        """

    def get_page(self, page_idx: int) -> Pyo3Page:
        """
        Retrieves a specific page from the document by index.

        # Arguments

        * `page_idx` - The zero-based index of the page to retrieve.

        # Returns

        A `Pyo3Page` instance or a Python error if the index is out of range or document is closed.
        """

    def pages(self) -> PageIterator:
        """Returns an iterator over pages (memory efficient for large PDFs)"""

    def __iter__(self) -> PageIterator:
        """
        Returns an iterator over all pages in the document.

        # Returns

        A `PyPageIterator` or a Python error if the document is closed.
        """

    def __enter__(self) -> Pyo3Doc:
        """
        Context manager entry point.

        # Returns

        A reference to self for use in `with` statements.
        """

    def __exit__(
        self, _exc_type: t.Any | None, _exc_val: t.Any | None, _exc_tb: t.Any | None
    ) -> bool:
        """
        Context manager exit point.

        Closes the document when exiting the `with` block.

        # Arguments

        * `_exc_type` - The exception type (if any).
        * `_exc_val` - The exception value (if any).
        * `_exc_tb` - The exception traceback (if any).

        # Returns

        `false` to indicate that exceptions should not be suppressed.
        """

@t.final
class Pyo3Page:
    """
    Represents a single page in a PDF document.

    Provides access to page properties like dimensions and rotation,
    as well as methods to extract objects and text from the page.
    """
    @property
    def page_idx(self) -> int:
        """Returns the index of the page within the document."""

    @property
    def width(self) -> float:
        """Returns the width of the page in points."""

    @property
    def height(self) -> float:
        """Returns the height of the page in points."""

    @property
    def rotation_degrees(self) -> float:
        """Returns the rotation of the page in degrees."""

    def is_valid(self) -> bool:
        """
        Checks if the page reference is still valid (document not closed).

        # Returns

        `true` if the page is valid, `false` otherwise.
        """

    def extract_objects(self) -> None:
        """
        Extracts all objects (characters, lines, rectangles) from the page.

        This method caches the extracted objects for subsequent access.
        """

    @property
    def objects(self) -> Objects | None:
        """
        Returns the extracted objects from the page.

        # Returns

        An `Objects` instance containing all extracted objects, or `None` if not yet extracted.
        """

    def clear_cache(self) -> None:
        """Clears the cached objects to free memory."""

@t.final
class PageIterator:
    """
    Iterator for traversing pages in a PDF document.

    This iterator is memory-efficient for large PDFs as it loads pages on demand.
    """
    def __iter__(self) -> PageIterator:
        """Returns self as the iterator."""

    def __next__(self) -> Pyo3Page:
        """
        Returns the next page in the iteration.

        Follows the Python [iterator protocol](https://docs.python.org/3/library/stdtypes.html#iterator.__next__):
        returns the next `Pyo3Page`, or raises `StopIteration` when exhausted.
        """

@t.final
class Edge:
    """
    Represents a line edge extracted from a PDF page.

    An edge can be either horizontal or vertical and includes
    position, width, and color information.
    """
    def __init__(
        self,
        orientation: t.Literal["h", "v"],
        x1: float,
        y1: float,
        x2: float,
        y2: float,
        width: float = 1.0,
        color: Color = (0, 0, 0, 255),
    ) -> None:
        """
        Creates a new Edge from Python.

        # Arguments

        * `orientation` - The orientation of the edge ("h" for horizontal, "v" for vertical).
        * `x1` - The left x-coordinate of the edge.
        * `y1` - The top y-coordinate of the edge.
        * `x2` - The right x-coordinate of the edge.
        * `y2` - The bottom y-coordinate of the edge.
        * `width` - The stroke width of the edge (default: 1.0).
        * `color` - The stroke color as an RGBA tuple (default: (0, 0, 0, 255)).
        """

    @property
    def x1(self) -> float:
        """Returns the left x-coordinate of the edge."""

    @property
    def y1(self) -> float:
        """Returns the top y-coordinate of the edge."""

    @property
    def x2(self) -> float:
        """Returns the right x-coordinate of the edge."""

    @property
    def y2(self) -> float:
        """Returns the bottom y-coordinate of the edge."""

    @property
    def width(self) -> float:
        """Returns the stroke width of the edge."""

    @property
    def color(self) -> Color:
        """Returns the color as an RGBA tuple."""

    @property
    def orientation(self) -> str:
        """Returns the orientation as a string ("h" or "v")."""

    def __repr__(self) -> str:
        """Returns a string representation of the edge for debugging."""

    def __eq__(self, other: t.Any) -> bool:
        """Checks equality based on coordinates."""

@t.final
class TableCell:
    """
    Represents a single cell in a table.

    Each cell has a bounding box and optional text content.
    """
    @property
    def text(self) -> str:
        """Returns the text content of the cell."""

    @property
    def bbox(self) -> BBox:
        """Returns the bounding box as a tuple (x1, y1, x2, y2)."""

@t.final
class Table:
    """
    Represents a table extracted from a PDF page.

    A table consists of cells organized in a grid structure.
    """
    @property
    def page_index(self) -> int:
        """The index of the page containing this table."""

    @property
    def text_extracted(self) -> bool:
        """Whether text has been extracted for cells."""

    @property
    def cells(self) -> list[TableCell]:
        """Returns a clone of all cells in the table."""

    @property
    def bbox(self) -> BBox:
        """Returns the bounding box as a tuple (x1, y1, x2, y2)."""

    @property
    def rows(self) -> list[CellGroup]:
        """
        Get rows
        Returns a vector of rows, where each row is a vector of cells or None
        """

    @property
    def columns(self) -> list[CellGroup]:
        """
        Get columns
        Returns a vector of columns, where each column is a vector of cells or None
        """

    def to_csv(self) -> str:
        """
        Converts the table to a CSV formatted string.

        # Returns

        A Result containing the CSV string, or an error if text has not been extracted.

        # Errors

        Returns a PyValueError if text_extracted is false.
        """

    def to_markdown(self) -> str:
        """
        Converts the table to a Markdown formatted string.

        # Returns

        A Result containing the Markdown string, or an error if text has not been extracted.

        # Errors

        Returns a PyValueError if text_extracted is false.
        """

    def to_html(self) -> str:
        """
        Converts the table to an HTML formatted string.

        # Returns

        A Result containing the HTML string, or an error if text has not been extracted.

        # Errors

        Returns a PyValueError if text_extracted is false.
        """

    def to_list(self) -> list[list[TableCellValue]]:
        """
        Converts the table to a list of rows; each element is a TableCellValue with text and merge flags.

        Each inner list is one row. TableCellValue has `text` (None when merged), `merged_left`,
        and `merged_top` so you can tell if the slot is merged with the cell to the left or above.

        # Errors

        Returns a PyValueError if text has not been extracted.
        """

@t.final
class Objects:
    """
    Container for all extracted objects from a PDF page.

    This struct holds all rectangles, lines, and characters found in a page.
    """
    @property
    def rects(self) -> list[Rect]:
        """All rectangles found in the page."""

    @property
    def lines(self) -> list[Line]:
        """All line segments found in the page."""

    @property
    def chars(self) -> list[Char]:
        """All text characters found in the page."""

@t.final
class Rect:
    """
    Represents a rectangle extracted from a PDF page.

    Rectangles are typically used as table cell borders or backgrounds.
    """
    @property
    def stroke_width(self) -> float:
        """The stroke width of the rectangle border."""

    @property
    def is_stroked(self) -> bool:
        """Whether the path is stroked."""

    @property
    def bbox(self) -> BBox:
        """Returns the bounding box as a tuple (x1, y1, x2, y2)."""

    @property
    def fill_color(self) -> Color:
        """Returns the fill color as an RGBA tuple."""

    @property
    def stroke_color(self) -> Color:
        """Returns the stroke color as an RGBA tuple."""

    @property
    def fill_mode(self) -> FillMode:
        """Returns the fill mode (NONE, WINDING, or EVEN_ODD)."""

@t.final
class Line:
    """
    Represents a line segment extracted from a PDF page.

    Lines can be straight or curved and are used for table borders.
    """
    @property
    def is_stroked(self) -> bool:
        """Whether the line is stroked."""

    @property
    def line_type(self) -> str:
        """Returns the line type as a string ("straight" or "curve")."""

    @property
    def points(self) -> list[Point]:
        """Returns the line points as a list of (x, y) tuples."""

    @property
    def stroke_color(self) -> Color:
        """Returns the stroke color as an RGBA tuple."""

    @property
    def fill_color(self) -> Color:
        """Returns the fill color as an RGBA tuple."""

    @property
    def width(self) -> float:
        """Returns the line width."""

    @property
    def fill_mode(self) -> FillMode:
        """Returns the fill mode (NONE, WINDING, or EVEN_ODD)."""

@t.final
class Char:
    """
    Represents a text character extracted from a PDF page.

    Each character includes its Unicode value, position, and rotation information.
    `unicode_char` is derived from Pdfium’s UTF-16 `unicode_value()` with surrogate-pair merging
    (one logical scalar per glyph where possible). See PDFium
    [`public/fpdf_text.h` (main)](https://pdfium.googlesource.com/pdfium/+/refs/heads/main/public/fpdf_text.h)
    for the UCS-2 / UTF-16 text APIs (`FPDFText_GetText`, `FPDFText_GetBoundedText`, etc.).
    """
    @property
    def unicode_char(self) -> str | None:
        """
        The Unicode string for this logical character (UTF-16 code units merged per
        PDFium `public/fpdf_text.h` on main when applicable).
        """

    @property
    def upright(self) -> bool:
        """Whether the character is upright (horizontal text)."""

    @property
    def bbox(self) -> BBox:
        """Returns the bounding box as a tuple (x1, y1, x2, y2)."""

    @property
    def rotation_degrees(self) -> float:
        """Returns the rotation of the character in degrees."""

@t.final
class CellGroup:
    """An owned version of CellGroup for Python interop."""
    @property
    def cells(self) -> list[TableCell | None]:
        """The cells in this group, with `None` for empty positions."""

    @property
    def bbox(self) -> BBox: ...

@t.final
class TableCellValue:
    """Python-exposed TableCellValue for to_list()."""
    @property
    def text(self) -> str | None: ...
    @property
    def merged_left(self) -> bool: ...
    @property
    def merged_top(self) -> bool: ...
    def __repr__(self) -> str:
        """Return repr as "(text, merged_left, merged_top)". Text is None or double-quoted (escaped); booleans are True/False."""

@t.final
class FillMode:
    """PDF path fill rule: mirrors pdfium-render's PdfPathFillMode for Python exposure."""

    ...

@t.final
class TfSettings:
    """
    Settings for table finding operations.

    Controls how edges are detected, snapped, joined, and how intersections
    are identified when finding tables in a PDF page.
    """
    def __init__(self, **kwargs: Unpack[TfSettingItems]) -> None:
        """
        Creates a new TfSettings instance from keyword arguments.

        # Arguments

        * `kwargs` - Optional dictionary of settings to override defaults.

        # Returns

        A new TfSettings instance.

        # Errors

        Returns PyValueError if any numeric value is negative.
        """

    @property
    def vertical_strategy(self) -> str: ...
    @property
    def horizontal_strategy(self) -> str: ...
    @property
    def snap_x_tolerance(self) -> float: ...
    @property
    def snap_y_tolerance(self) -> float: ...
    @property
    def join_x_tolerance(self) -> float: ...
    @property
    def join_y_tolerance(self) -> float: ...
    @property
    def edge_min_length(self) -> float: ...
    @property
    def edge_min_length_prefilter(self) -> float: ...
    @property
    def min_words_vertical(self) -> int: ...
    @property
    def min_words_horizontal(self) -> int: ...
    @property
    def intersection_x_tolerance(self) -> float: ...
    @property
    def intersection_y_tolerance(self) -> float: ...
    @property
    def include_single_cell(self) -> bool: ...
    @property
    def min_rows(self) -> int | None: ...
    @property
    def min_columns(self) -> int | None: ...
    @property
    def text_settings(self) -> WordsExtractSettings: ...
    @property
    def text_need_strip(self) -> bool: ...
    @property
    def text_x_tolerance(self) -> float: ...
    @property
    def text_y_tolerance(self) -> float: ...
    @property
    def text_keep_blank_chars(self) -> bool: ...
    @property
    def text_use_text_flow(self) -> bool: ...
    @property
    def text_read_in_clockwise(self) -> bool: ...
    @property
    def text_split_at_punctuation(self) -> str | None: ...
    @property
    def text_expand_ligatures(self) -> bool: ...
    @property
    def explicit_h_edges(self) -> list[Edge] | None: ...
    @property
    def explicit_v_edges(self) -> list[Edge] | None: ...
    @property
    def exclude_background_colored_edges(self) -> bool: ...
    @property
    def close_unclosed_boundaries(self) -> bool: ...
    @vertical_strategy.setter
    def vertical_strategy(self, value: str) -> None: ...
    @horizontal_strategy.setter
    def horizontal_strategy(self, value: str) -> None: ...
    @snap_x_tolerance.setter
    def snap_x_tolerance(self, value: float) -> None: ...
    @snap_y_tolerance.setter
    def snap_y_tolerance(self, value: float) -> None: ...
    @join_x_tolerance.setter
    def join_x_tolerance(self, value: float) -> None: ...
    @join_y_tolerance.setter
    def join_y_tolerance(self, value: float) -> None: ...
    @edge_min_length.setter
    def edge_min_length(self, value: float) -> None: ...
    @edge_min_length_prefilter.setter
    def edge_min_length_prefilter(self, value: float) -> None: ...
    @min_words_vertical.setter
    def min_words_vertical(self, value: int) -> None: ...
    @min_words_horizontal.setter
    def min_words_horizontal(self, value: int) -> None: ...
    @intersection_x_tolerance.setter
    def intersection_x_tolerance(self, value: float) -> None: ...
    @intersection_y_tolerance.setter
    def intersection_y_tolerance(self, value: float) -> None: ...
    @include_single_cell.setter
    def include_single_cell(self, value: bool) -> None: ...
    @min_rows.setter
    def min_rows(self, value: int | None) -> None: ...
    @min_columns.setter
    def min_columns(self, value: int | None) -> None: ...
    @text_settings.setter
    def text_settings(self, value: WordsExtractSettings) -> None: ...
    @text_need_strip.setter
    def text_need_strip(self, value: bool) -> None: ...
    @text_x_tolerance.setter
    def text_x_tolerance(self, value: float) -> None: ...
    @text_y_tolerance.setter
    def text_y_tolerance(self, value: float) -> None: ...
    @text_keep_blank_chars.setter
    def text_keep_blank_chars(self, value: bool) -> None: ...
    @text_use_text_flow.setter
    def text_use_text_flow(self, value: bool) -> None: ...
    @text_read_in_clockwise.setter
    def text_read_in_clockwise(self, value: bool) -> None: ...
    @text_split_at_punctuation.setter
    def text_split_at_punctuation(self, value: str | None) -> None: ...
    @text_expand_ligatures.setter
    def text_expand_ligatures(self, value: bool) -> None: ...
    @explicit_h_edges.setter
    def explicit_h_edges(self, value: list[Edge] | None) -> None: ...
    @explicit_v_edges.setter
    def explicit_v_edges(self, value: list[Edge] | None) -> None: ...
    @exclude_background_colored_edges.setter
    def exclude_background_colored_edges(self, value: bool) -> None: ...
    @close_unclosed_boundaries.setter
    def close_unclosed_boundaries(self, value: bool) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: t.Any) -> bool: ...

@t.final
class WordsExtractSettings:
    """
    Settings for word extraction from PDF text.

    Controls how characters are grouped into words, including
    tolerance values and text direction handling.
    """
    def __init__(self, **kwargs: Unpack[WordsExtractSettingsItems]) -> None:
        """
        Creates a new WordsExtractSettings instance from keyword arguments.

        # Arguments

        * `kwargs` - Optional dictionary of settings to override defaults.

        # Returns

        A new WordsExtractSettings instance.

        # Errors

        Returns PyValueError if any numeric value is negative.
        """

    @property
    def x_tolerance(self) -> float: ...
    @property
    def y_tolerance(self) -> float: ...
    @property
    def keep_blank_chars(self) -> bool: ...
    @property
    def use_text_flow(self) -> bool: ...
    @property
    def text_read_in_clockwise(self) -> bool: ...
    @property
    def split_at_punctuation(self) -> str | None: ...
    @property
    def expand_ligatures(self) -> bool: ...
    @property
    def need_strip(self) -> bool: ...
    @x_tolerance.setter
    def x_tolerance(self, value: float) -> None: ...
    @y_tolerance.setter
    def y_tolerance(self, value: float) -> None: ...
    @keep_blank_chars.setter
    def keep_blank_chars(self, value: bool) -> None: ...
    @use_text_flow.setter
    def use_text_flow(self, value: bool) -> None: ...
    @text_read_in_clockwise.setter
    def text_read_in_clockwise(self, value: bool) -> None: ...
    @split_at_punctuation.setter
    def split_at_punctuation(self, value: str | None) -> None: ...
    @expand_ligatures.setter
    def expand_ligatures(self, value: bool) -> None: ...
    @need_strip.setter
    def need_strip(self, value: bool) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: t.Any) -> bool: ...

def find_all_cells_bboxes(
    page: Pyo3Page | None = None,
    clip: BBox | None = None,
    tf_settings: TfSettings | None = None,
    **kwargs: Unpack[TfSettingItems],
) -> list[BBox]:
    """
    Finds all table cell bounding boxes in a PDF page or from explicit edges.

    # Arguments

    * `page` - The PDF page to analyze. Can be None only if both
    horizontal_strategy and vertical_strategy are set to "explicit".
    * `clip` - Optional clip region (x1, y1, x2, y2). If provided, only edges
    within this region are used for cell detection.
    * `tf_settings` - Optional TableFinder settings object.
    * `kwargs` - Optional keyword arguments for settings.

    # Returns

    A list of bounding boxes (x1, y1, x2, y2) for each detected cell.

    # Raises

    RuntimeError: If page is None and either strategy is not "explicit".
    """

def find_tables_from_cells(
    cells: list,
    extract_text: bool,
    page: Pyo3Page | None = None,
    tf_settings: TfSettings | None = None,
    **kwargs: Unpack[TfSettingItems],
) -> list[Table]:
    """
    Constructs tables from a list of cell bounding boxes.

    # Arguments

    * `cells` - A list of cell bounding boxes.
    * `extract_text` - Whether to extract text content from cells.
    * `pdf_page` - The PDF page (required if extract_text is true).
    * `we_settings` - Optional word extraction settings.
    * `need_strip` - Whether to strip leading/trailing whitespace from cell text (default: true).
    * `kwargs` - Optional keyword arguments for settings.

    # Returns

    A list of Table objects constructed from the cells.
    """

def find_tables(
    page: Pyo3Page | None = None,
    extract_text: bool = True,
    clip: BBox | None = None,
    tf_settings: TfSettings | None = None,
    **kwargs: Unpack[TfSettingItems],
) -> list[Table]:
    """
    Finds all tables in a PDF page.

    # Arguments

    * `page` - The PDF page to analyze. Can be None only if both strategies are explicit
    and extract_text is false.
    * `extract_text` - Whether to extract text content from table cells.
    * `clip` - Optional clip region (x1, y1, x2, y2). If provided, only edges
    within this region are used for table detection.
    * `tf_settings` - Optional TableFinder settings object.
    * `kwargs` - Optional keyword arguments for settings.

    # Returns

    A list of Table objects found in the page.

    # Errors

    Returns an error if:
    - `page` is None and `extract_text` is true
    - `page` is None and either strategy is not explicit
    """

def get_edges(
    page: Pyo3Page | None = None,
    tf_settings: TfSettings | None = None,
    **kwargs: Unpack[TfSettingItems],
) -> dict[t.Literal["v", "h"], list[Edge]]:
    """
    Extracts edges (lines and rectangle borders) from a PDF page or from explicit edges.

    # Arguments

    * `page` - The PDF page to extract edges from. Can be None only if both
    horizontal_strategy and vertical_strategy are set to "explicit".
    * `tf_settings` - Optional TfSettings object for edge extraction.
    * `kwargs` - Optional keyword arguments for settings.

    # Returns

    A dictionary with keys "h" (horizontal edges) and "v" (vertical edges).

    # Raises

    RuntimeError: If page is None and either strategy is not "explicit".
    """

def get_intersections_from_edges(
    h_edges: list[Edge],
    v_edges: list[Edge],
    tf_settings: TfSettings | None = None,
    **kwargs: Unpack[TfSettingItems],
) -> dict[Point, dict[t.Literal["v", "h"], list[Edge]]]:
    """
    Computes intersection points from a set of horizontal and vertical edges.

    # Arguments

    * `h_edges` - A list of horizontal edges (as returned by ``get_edges``).
    * `v_edges` - A list of vertical edges (as returned by ``get_edges``).
    * `tf_settings` - Optional TfSettings object for tolerance configuration.
    * `kwargs` - Optional keyword arguments for settings.

    # Returns

    A dictionary mapping ``(x, y)`` intersection points to a dict with keys
    ``"h"`` and ``"v"`` containing the edges that pass through that point.
    """
